export interface Product {
  id: number
  name: string
  brand: string
  price: number
  originalPrice: number
  image: string
  rating: number
  reviews: number
  stock: number
  isNew?: boolean
}

export const products: Product[] = [
  {
    id: 1,
    name: "Apple iPhone 15 Pro Max 256GB Natural Titanium",
    brand: "Apple",
    price: 1199,
    originalPrice: 1299,
    image: "/iphone-15-pro-max-display.png",
    rating: 4.8,
    reviews: 2453,
    stock: 15,
    isNew: true,
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra 512GB Titanium Gray",
    brand: "Samsung",
    price: 1099,
    originalPrice: 1299,
    image: "/samsung-galaxy-s24-ultra.png",
    rating: 4.7,
    reviews: 1876,
    stock: 23,
    isNew: true,
  },
  {
    id: 3,
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    brand: "Sony",
    price: 299,
    originalPrice: 399,
    image: "/sony-wh1000xm5-headphones.jpg",
    rating: 4.9,
    reviews: 5621,
    stock: 8,
  },
  {
    id: 4,
    name: "Nike Air Max 270 React Men's Running Shoes",
    brand: "Nike",
    price: 129,
    originalPrice: 170,
    image: "/nike-air-max-270.png",
    rating: 4.5,
    reviews: 3245,
    stock: 45,
  },
  {
    id: 5,
    name: "Apple MacBook Pro 14-inch M3 Pro 18GB 512GB",
    brand: "Apple",
    price: 1999,
    originalPrice: 2199,
    image: "/macbook-pro-14-m3.jpg",
    rating: 4.9,
    reviews: 1234,
    stock: 5,
    isNew: true,
  },
  {
    id: 6,
    name: "Dyson V15 Detect Absolute Cordless Vacuum",
    brand: "Dyson",
    price: 649,
    originalPrice: 749,
    image: "/dyson-v15-vacuum.png",
    rating: 4.7,
    reviews: 2876,
    stock: 12,
  },
  {
    id: 7,
    name: "LG OLED C3 65-inch 4K Smart TV",
    brand: "LG",
    price: 1499,
    originalPrice: 1999,
    image: "/lg-oled-c3-tv.jpg",
    rating: 4.8,
    reviews: 4532,
    stock: 7,
  },
  {
    id: 8,
    name: "Apple AirPods Pro 2nd Generation",
    brand: "Apple",
    price: 199,
    originalPrice: 249,
    image: "/airpods-pro-2.png",
    rating: 4.8,
    reviews: 8765,
    stock: 34,
  },
  {
    id: 9,
    name: "Nintendo Switch OLED Model White",
    brand: "Nintendo",
    price: 299,
    originalPrice: 349,
    image: "/nintendo-switch-oled.jpg",
    rating: 4.7,
    reviews: 6543,
    stock: 18,
  },
  {
    id: 10,
    name: "Bose QuietComfort Ultra Earbuds",
    brand: "Bose",
    price: 279,
    originalPrice: 329,
    image: "/bose-quietcomfort-ultra-earbuds.jpg",
    rating: 4.6,
    reviews: 2134,
    stock: 22,
  },
  {
    id: 11,
    name: "Adidas Ultraboost 23 Running Shoes",
    brand: "Adidas",
    price: 159,
    originalPrice: 190,
    image: "/adidas-ultraboost-23.jpg",
    rating: 4.6,
    reviews: 4321,
    stock: 56,
  },
  {
    id: 12,
    name: "Canon EOS R6 Mark II Mirrorless Camera",
    brand: "Canon",
    price: 2299,
    originalPrice: 2499,
    image: "/canon-eos-r6-mark-ii.jpg",
    rating: 4.9,
    reviews: 987,
    stock: 3,
    isNew: true,
  },
]
